"""create scan and scan_error tables

Revision ID: 817b75001d2d
Revises:
Create Date: 2026-10-08 14:07:28.953696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "817b75001d2d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan",
        sa.Column("id", sa.Uuid(), nullable=False, comment="扫描记录标识；领域模型尚无 scan id，由持久化层生成"),
        sa.Column(
            "repository_id",
            sa.String(length=200),
            nullable=False,
            comment="S1/S2 定位键之一；调用方提供的不透明标识，ADR-010 要求不含 ':'",
        ),
        sa.Column(
            "revision",
            sa.String(length=100),
            nullable=True,
            comment="S1 定位键之一；failed 结局允许为空（采集阶段就失败时拿不到 revision）",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="S1/S2 结局；ADR-011 闭合集合 completed / partial / failed",
        ),
        sa.Column(
            "files_collected",
            sa.Integer(),
            nullable=False,
            comment="S1 漏斗计数之一；来自 ScanStats，只存无法从图推导的阶段计数",
        ),
        sa.Column(
            "files_analyzed",
            sa.Integer(),
            nullable=False,
            comment="S1 漏斗计数之一；与 files_collected 共同支撑失败率与解析质量趋势",
        ),
        sa.Column(
            "files_failed", sa.Integer(), nullable=False, comment="S1 漏斗计数之一；与 code 维度的聚合共同定位质量退化"
        ),
        sa.Column(
            "graph_schema_version",
            sa.Integer(),
            nullable=True,
            comment="S1 读 Artifact 时判定契约版本（ADR-010 的 schema_version）",
        ),
        sa.Column(
            "parser_version",
            sa.String(length=100),
            nullable=True,
            comment="S1 判定产出者实现版本；与契约版本相互独立（ADR-010）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="S2 排序键；写入时刻由数据库生成，避免依赖应用时钟",
        ),
        sa.CheckConstraint(
            "status = 'failed' OR (graph_schema_version IS NOT NULL AND parser_version IS NOT NULL)",
            name=op.f("ck_scan_graph_metadata_required_unless_failed"),
        ),
        sa.CheckConstraint(
            "status = 'failed' OR revision IS NOT NULL", name=op.f("ck_scan_revision_required_unless_failed")
        ),
        sa.CheckConstraint("status IN ('completed', 'partial', 'failed')", name=op.f("ck_scan_status_closed_set")),
        sa.CheckConstraint("files_analyzed + files_failed <= files_collected", name=op.f("ck_scan_stats_funnel")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan")),
        comment="扫描元数据；S1 按 (repository_id, revision) 定位结局与产物契约版本，S2 按仓库列历史（倒序）。CodeGraph 本体是 JSON Artifact，不在此表。",
    )
    op.create_index("ix_scan_repository_id_created_at", "scan", ["repository_id", "created_at"], unique=False)
    op.create_table(
        "scan_error",
        sa.Column("id", sa.Uuid(), nullable=False, comment="错误记录标识；领域模型无此 id，由持久化层生成"),
        sa.Column("scan_id", sa.Uuid(), nullable=False, comment="E1 归属；随 scan 级联删除，错误不能脱离扫描独立存在"),
        sa.Column(
            "stage",
            sa.String(length=20),
            nullable=False,
            comment="E1 阶段；ADR-011 闭合集合 collect / analyze / persist",
        ),
        sa.Column(
            "code",
            sa.String(length=40),
            nullable=False,
            comment="E2 稳定错误码（ADR-011 闭合集合）；新增码属于契约变更",
        ),
        sa.Column(
            "severity",
            sa.String(length=10),
            nullable=False,
            comment="E1 严重度；local = 局部失败仍可产出图，fatal = 整体失败",
        ),
        sa.Column(
            "message",
            sa.String(length=1000),
            nullable=False,
            comment="E1 面向人的说明；机器判定一律用 code，不解析本列",
        ),
        sa.Column(
            "file_path",
            sa.String(length=1000),
            nullable=True,
            comment="E1 归属文件（仓库根相对 POSIX 路径）；错误不一定归属具体文件",
        ),
        sa.CheckConstraint(
            "code IN ('path_invalid', 'git_error', 'file_unreadable', 'file_encoding', 'file_disappeared', 'symlink_rejected', 'syntax_error', 'storage_error')",
            name=op.f("ck_scan_error_code_closed_set"),
        ),
        sa.CheckConstraint("severity IN ('local', 'fatal')", name=op.f("ck_scan_error_severity_closed_set")),
        sa.CheckConstraint("stage IN ('collect', 'analyze', 'persist')", name=op.f("ck_scan_error_stage_closed_set")),
        sa.ForeignKeyConstraint(["scan_id"], ["scan.id"], name=op.f("fk_scan_error_scan_id_scan"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_error")),
        comment="扫描的结构化错误；E1 按 scan_id 取某次扫描的全部错误，E2 按 code 聚合定位质量退化（时间维度经 scan.created_at 关联）。",
    )
    op.create_index("ix_scan_error_code", "scan_error", ["code"], unique=False)
    op.create_index("ix_scan_error_scan_id", "scan_error", ["scan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scan_error_scan_id", table_name="scan_error")
    op.drop_index("ix_scan_error_code", table_name="scan_error")
    op.drop_table("scan_error")
    op.drop_index("ix_scan_repository_id_created_at", table_name="scan")
    op.drop_table("scan")
    # ### end Alembic commands ###
